### ISSUE TITLE
BLE Private Key Deployment / How?

### ISSUE THREAD

**Issue by baylanger** [raphmur/tesla-local-control-addon#3]
Trying to figure out the requirements for this addon to deploy the private key.

Is pairing between HAOS and the car needed before deploying the key? If so... how? 🤔 

In the addon when pressing the button "Deploy Key", is this all automatic or does the end user need to be in the car's Bluetooth many?

My current BLE dongle (ASUS USB-BT500) is assigned to the HAOS VM.
Currently have the following in HA config file device_tracker.yaml :
```
- platform: bluetooth_le_tracker
  new_device_defaults:
    track_new_devices: true
  interval_seconds: 10
  consider_home: 180
```
Perhaps the above is interfering with this add-on? I'm not sure yet.

I noticed code changes around BLE, once 0.0.4 shows up I'll upgrade and try again.
